id: A3DE5C4D5
title: Aspiration for Electric Lamps
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:08:30.874070
  last_modified_at: 2022-03-01 00:08:30.874076
